export interface Category {
  id: string;
  name: string;
  description: string;
  items: string[];
  image: string;
  alt: string;
}

export interface Product {
  name: string;
  description: string;
  image: string;
  alt: string;
}

export interface CustomerSegment {
  title: string;
  icon: string;
  items: string[];
  image: string;
  alt: string;
}

export interface PortfolioItem {
  title: string;
  category: string;
  image: string;
  alt: string;
}

export interface FAQItem {
  question: string;
  answer: string;
}

export interface BusinessSolution {
  title: string;
  description: string;
  icon: string;
}

export interface ProcessStep {
  step: number;
  title: string;
  description: string;
  icon: string;
}

export interface WhyChooseItem {
  title: string;
  description: string;
  icon: string;
}

export const categories: Category[] = [
  {
    id: 'visiting-cards',
    name: 'Visiting Cards',
    description: 'Standard, classic, premium, and custom shape visiting cards.',
    items: ['Standard', 'Classic', 'Rounded Corner', 'Transparent', 'Spot UV', 'Custom Shape'],
    image: '/images/visiting_cards.jpg',
    alt: 'Visiting cards on a marble surface',
  },
  {
    id: 'stationery',
    name: 'Stationery, Letterheads & Notebooks',
    description: 'Business stationery, letterheads, and customized notebooks.',
    items: ['Letterheads', 'Bill Books', 'Envelopes', 'ID Cards', 'Notebooks', 'Diaries'],
    image: '/images/stationery.jpg',
    alt: 'Stationery items on a desk',
  },
  {
    id: 'stamps',
    name: 'Stamps and Ink',
    description: 'Self-inking stamps, basic rubber stamps, and pocket stamps.',
    items: ['Self Inking Stamps', 'Basic Rubber Stamps', 'Pocket Stamps', 'Name Stamps'],
    image: '/images/rubber_stamps.jpg',
    alt: 'Rubber stamp on paper',
  },
  {
    id: 'marketing-materials',
    name: 'Signs, Posters & Marketing Materials',
    description: 'Standees, posters, banners, and promotional canopy tents.',
    items: ['Standees', 'Posters', 'Banners', 'Flyers', 'Brochures', 'Canopy Tents'],
    image: '/images/marketing_materials.jpg',
    alt: 'Folded brochures and marketing materials',
  },
  {
    id: 'packaging',
    name: 'Labels, Stickers & Packaging',
    description: 'Custom stickers, packaging labels, carry bags, and boxes.',
    items: ['Custom Stickers', 'Return Address Labels', 'Carry Bags', 'Courier Bags', 'Boxes'],
    image: '/images/packaging_boxes.jpg',
    alt: 'Custom printed packaging box and label',
  },
  {
    id: 'apparel',
    name: 'Clothing, Caps & Bags',
    description: 'Custom T-shirts, premium polo shirts, jackets, caps, and bags.',
    items: ["Men's T-Shirts", "Women's T-Shirts", 'Jackets', 'Custom Caps', 'Laptop Bags'],
    image: '/images/apparel.jpg',
    alt: 'Custom printed T-shirt on a hanger',
  },
  {
    id: 'gifts',
    name: 'Mugs, Albums & Gifts',
    description: 'Personalised mugs, photo albums, canvas prints, and corporate gifts.',
    items: ['Photo Albums', 'Canvas Prints', 'Personalised Mugs', 'Corporate Gifts', 'Mouse Pads'],
    image: '/images/photo_gifts.jpg',
    alt: 'Personalized coffee mug',
  },
  {
    id: 'pens',
    name: 'Pens',
    description: 'Premium metal roller pens, engraved pens, and promotional pens.',
    items: ['Customized Pens', 'Premium Metal Pens', 'Luxury Pens', 'Promotional Pens'],
    image: '/images/pens.jpg',
    alt: 'Premium metallic pen on paper',
  },
  {
    id: 'drinkware',
    name: 'Drinkware',
    description: 'Custom water bottles, vacuum flasks, and frosted beer mugs.',
    items: ['Custom Water Bottles', 'Stainless Steel Sipper', 'Vacuum Flasks', 'Beer Mugs'],
    image: '/images/drinkware.jpg',
    alt: 'Stainless steel water bottle',
  },
  {
    id: 'polo-shirts',
    name: 'Custom Polo T-shirts',
    description: 'Branded polo t-shirts including Puma, Adidas, and more.',
    items: ['Premium Polo', 'Puma Polo', 'US Polo Assn', 'Arrow Polo'],
    image: '/images/polo_shirts.jpg',
    alt: 'Custom polo shirt',
  },
  {
    id: 'winterwear',
    name: 'Custom Winterwear',
    description: 'Fleece jackets, hoodies, puffers, and sweatshirts.',
    items: ['Hoodies', 'Fleece Jackets', 'Puffer Jackets', 'Crewneck Sweatshirts'],
    image: '/images/winterwear.jpg',
    alt: 'Person wearing a winter hoodie',
  }
];

export const categoryDetails: Record<string, {name: string; description: string; image: string}[]> = {
  'visiting-cards': [
    { name: "Standard Visiting Cards", description: "High quality custom standard visiting cards for your business needs.", image: "https://images.pexels.com/photos/9878733/pexels-photo-9878733.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Classic Visiting Cards", description: "High quality custom classic visiting cards for your business needs.", image: "https://images.pexels.com/photos/5706015/pexels-photo-5706015.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Rounded Corner Visiting Cards", description: "High quality custom rounded corner visiting cards for your business needs.", image: "https://images.pexels.com/photos/5706020/pexels-photo-5706020.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Square Visiting Cards", description: "High quality custom square visiting cards for your business needs.", image: "https://images.pexels.com/photos/8947634/pexels-photo-8947634.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Leaf Visiting Cards", description: "High quality custom leaf visiting cards for your business needs.", image: "https://images.pexels.com/photos/6224/hands-people-woman-working.jpg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Oval Visiting Cards", description: "High quality custom oval visiting cards for your business needs.", image: "https://images.pexels.com/photos/6373155/pexels-photo-6373155.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Circle Visiting Cards", description: "High quality custom circle visiting cards for your business needs.", image: "https://images.pexels.com/photos/3391851/pexels-photo-3391851.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Shape Visiting Cards", description: "High quality custom custom shape visiting cards for your business needs.", image: "https://images.pexels.com/photos/9878733/pexels-photo-9878733.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "QR Code Visiting Cards", description: "High quality custom qr code visiting cards for your business needs.", image: "https://images.pexels.com/photos/5706015/pexels-photo-5706015.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Spot UV Visiting Cards", description: "High quality custom spot uv visiting cards for your business needs.", image: "https://images.pexels.com/photos/5706020/pexels-photo-5706020.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Raised Foil Visiting Cards", description: "High quality custom raised foil visiting cards for your business needs.", image: "https://images.pexels.com/photos/8947634/pexels-photo-8947634.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Glossy Visiting Cards", description: "High quality custom glossy visiting cards for your business needs.", image: "https://images.pexels.com/photos/6224/hands-people-woman-working.jpg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Matte Visiting Cards", description: "High quality custom matte visiting cards for your business needs.", image: "https://images.pexels.com/photos/6373155/pexels-photo-6373155.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Bulk Visiting Cards", description: "High quality custom bulk visiting cards for your business needs.", image: "https://images.pexels.com/photos/3391851/pexels-photo-3391851.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Magnetic Visiting Cards", description: "High quality custom magnetic visiting cards for your business needs.", image: "https://images.pexels.com/photos/9878733/pexels-photo-9878733.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Transparent Visiting Cards", description: "High quality custom transparent visiting cards for your business needs.", image: "https://images.pexels.com/photos/5706015/pexels-photo-5706015.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Premium Plus Visiting Cards", description: "High quality custom premium plus visiting cards for your business needs.", image: "https://images.pexels.com/photos/5706020/pexels-photo-5706020.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Non-Tearable Visiting Cards", description: "High quality custom non-tearable visiting cards for your business needs.", image: "https://images.pexels.com/photos/8947634/pexels-photo-8947634.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Velvet Touch Visiting Cards", description: "High quality custom velvet touch visiting cards for your business needs.", image: "https://images.pexels.com/photos/6224/hands-people-woman-working.jpg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Pearl Visiting Cards", description: "High quality custom pearl visiting cards for your business needs.", image: "https://images.pexels.com/photos/6373155/pexels-photo-6373155.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Kraft Visiting Cards", description: "High quality custom kraft visiting cards for your business needs.", image: "https://images.pexels.com/photos/3391851/pexels-photo-3391851.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Diamond Visiting Cards", description: "High quality custom diamond visiting cards for your business needs.", image: "https://images.pexels.com/photos/9878733/pexels-photo-9878733.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Visiting Card Holders", description: "High quality custom visiting card holders for your business needs.", image: "https://images.pexels.com/photos/5706015/pexels-photo-5706015.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Engraved Metal Card Holders", description: "High quality custom engraved metal card holders for your business needs.", image: "https://images.pexels.com/photos/5706020/pexels-photo-5706020.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Metal Card Holder", description: "High quality custom metal card holder for your business needs.", image: "https://images.pexels.com/photos/8947634/pexels-photo-8947634.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Leatherite Card Holder", description: "High quality custom leatherite card holder for your business needs.", image: "https://images.pexels.com/photos/6224/hands-people-woman-working.jpg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Premium Metal Card Holders", description: "High quality custom premium metal card holders for your business needs.", image: "https://images.pexels.com/photos/6373155/pexels-photo-6373155.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
  ],
  'stationery': [
    { name: "Letterheads", description: "High quality custom letterheads for your business needs.", image: "https://images.pexels.com/photos/7718630/pexels-photo-7718630.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Letterhead Pads", description: "High quality custom custom letterhead pads for your business needs.", image: "https://images.pexels.com/photos/733857/pexels-photo-733857.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Bill Books", description: "High quality custom bill books for your business needs.", image: "https://images.pexels.com/photos/1766604/pexels-photo-1766604.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Envelopes", description: "High quality custom envelopes for your business needs.", image: "https://images.pexels.com/photos/1109541/pexels-photo-1109541.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Envelope Seals", description: "High quality custom envelope seals for your business needs.", image: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Pen Drive", description: "High quality custom custom pen drive for your business needs.", image: "https://images.pexels.com/photos/4553364/pexels-photo-4553364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Laptop Skins", description: "High quality custom laptop skins for your business needs.", image: "https://images.pexels.com/photos/7718630/pexels-photo-7718630.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Bulk Letterheads", description: "High quality custom bulk letterheads for your business needs.", image: "https://images.pexels.com/photos/733857/pexels-photo-733857.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Gift Tags", description: "High quality custom gift tags for your business needs.", image: "https://images.pexels.com/photos/1766604/pexels-photo-1766604.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Gaming Mousepads", description: "High quality custom gaming mousepads for your business needs.", image: "https://images.pexels.com/photos/1109541/pexels-photo-1109541.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Lanyards", description: "High quality custom lanyards for your business needs.", image: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "ID Cards", description: "High quality custom id cards for your business needs.", image: "https://images.pexels.com/photos/4553364/pexels-photo-4553364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Invoice Books", description: "High quality custom invoice books for your business needs.", image: "https://images.pexels.com/photos/7718630/pexels-photo-7718630.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Note Cards", description: "High quality custom note cards for your business needs.", image: "https://images.pexels.com/photos/733857/pexels-photo-733857.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Certificates", description: "High quality custom custom certificates for your business needs.", image: "https://images.pexels.com/photos/1766604/pexels-photo-1766604.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Awards", description: "High quality custom awards for your business needs.", image: "https://images.pexels.com/photos/1109541/pexels-photo-1109541.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Coasters", description: "High quality custom coasters for your business needs.", image: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Employee Welcome Kit", description: "High quality custom employee welcome kit for your business needs.", image: "https://images.pexels.com/photos/4553364/pexels-photo-4553364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Cash Vouchers", description: "High quality custom cash vouchers for your business needs.", image: "https://images.pexels.com/photos/7718630/pexels-photo-7718630.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Paper Identity Cards", description: "High quality custom paper identity cards for your business needs.", image: "https://images.pexels.com/photos/733857/pexels-photo-733857.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Border Stitched Mousepads", description: "High quality custom border stitched mousepads for your business needs.", image: "https://images.pexels.com/photos/1766604/pexels-photo-1766604.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Personalised Notebooks", description: "High quality custom personalised notebooks for your business needs.", image: "https://images.pexels.com/photos/1109541/pexels-photo-1109541.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Diary with Pen Holder", description: "High quality custom diary with pen holder for your business needs.", image: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Personalised A5 Diary", description: "High quality custom personalised a5 diary for your business needs.", image: "https://images.pexels.com/photos/4553364/pexels-photo-4553364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Diary with Magnetic Lock", description: "High quality custom diary with magnetic lock for your business needs.", image: "https://images.pexels.com/photos/7718630/pexels-photo-7718630.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Notebook A4 Size", description: "High quality custom notebook a4 size for your business needs.", image: "https://images.pexels.com/photos/733857/pexels-photo-733857.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Notepads", description: "High quality custom custom notepads for your business needs.", image: "https://images.pexels.com/photos/1766604/pexels-photo-1766604.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Keychains", description: "High quality custom custom keychains for your business needs.", image: "https://images.pexels.com/photos/1109541/pexels-photo-1109541.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Wedding Invitations", description: "High quality custom wedding invitations for your business needs.", image: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Save The Date Cards", description: "High quality custom save the date cards for your business needs.", image: "https://images.pexels.com/photos/4553364/pexels-photo-4553364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Wedding Menu", description: "High quality custom wedding menu for your business needs.", image: "https://images.pexels.com/photos/7718630/pexels-photo-7718630.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Wedding Programmes", description: "High quality custom wedding programmes for your business needs.", image: "https://images.pexels.com/photos/733857/pexels-photo-733857.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Thank You Cards", description: "High quality custom thank you cards for your business needs.", image: "https://images.pexels.com/photos/1766604/pexels-photo-1766604.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Birthday Invitations", description: "High quality custom birthday invitations for your business needs.", image: "https://images.pexels.com/photos/1109541/pexels-photo-1109541.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Party Invitations", description: "High quality custom party invitations for your business needs.", image: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Moving Announcements", description: "High quality custom moving announcements for your business needs.", image: "https://images.pexels.com/photos/4553364/pexels-photo-4553364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Presentation Folders", description: "High quality custom presentation folders for your business needs.", image: "https://images.pexels.com/photos/7718630/pexels-photo-7718630.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Ring Binder File", description: "High quality custom ring binder file for your business needs.", image: "https://images.pexels.com/photos/733857/pexels-photo-733857.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Presentation File with Pocket", description: "High quality custom presentation file with pocket for your business needs.", image: "https://images.pexels.com/photos/1766604/pexels-photo-1766604.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Document File", description: "High quality custom custom document file for your business needs.", image: "https://images.pexels.com/photos/1109541/pexels-photo-1109541.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Gift Wrapping Paper", description: "High quality custom gift wrapping paper for your business needs.", image: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Paper Wrist Bands", description: "High quality custom custom paper wrist bands for your business needs.", image: "https://images.pexels.com/photos/4553364/pexels-photo-4553364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "USB Flash Drive", description: "High quality custom usb flash drive for your business needs.", image: "https://images.pexels.com/photos/7718630/pexels-photo-7718630.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Perfect Binding Booklets", description: "High quality custom perfect binding booklets for your business needs.", image: "https://images.pexels.com/photos/733857/pexels-photo-733857.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Mats", description: "High quality custom mats for your business needs.", image: "https://images.pexels.com/photos/1766604/pexels-photo-1766604.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Recognition Plaques", description: "High quality custom recognition plaques for your business needs.", image: "https://images.pexels.com/photos/1109541/pexels-photo-1109541.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Star Performer Awards", description: "High quality custom star performer awards for your business needs.", image: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Classic Executive Diary", description: "High quality custom classic executive diary for your business needs.", image: "https://images.pexels.com/photos/4553364/pexels-photo-4553364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Office Stationery Kit", description: "High quality custom office stationery kit for your business needs.", image: "https://images.pexels.com/photos/7718630/pexels-photo-7718630.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Long Notebooks", description: "High quality custom custom long notebooks for your business needs.", image: "https://images.pexels.com/photos/733857/pexels-photo-733857.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Business Envelopes", description: "High quality custom business envelopes for your business needs.", image: "https://images.pexels.com/photos/1766604/pexels-photo-1766604.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Worldview 2026 Leather Diary", description: "High quality custom worldview 2026 leather diary for your business needs.", image: "https://images.pexels.com/photos/1109541/pexels-photo-1109541.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Gold Foil Wedding Invitations", description: "High quality custom gold foil wedding invitations for your business needs.", image: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Photo Keychains", description: "High quality custom photo keychains for your business needs.", image: "https://images.pexels.com/photos/4553364/pexels-photo-4553364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Mousepad with Wrist Support", description: "High quality custom mousepad with wrist support for your business needs.", image: "https://images.pexels.com/photos/7718630/pexels-photo-7718630.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Bulk Diaries", description: "High quality custom bulk diaries for your business needs.", image: "https://images.pexels.com/photos/733857/pexels-photo-733857.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
  ],
  'stamps': [
    { name: "Self Inking Stamps", description: "High quality custom self inking stamps for your business needs.", image: "https://images.pexels.com/photos/3800060/pexels-photo-3800060.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Basic Rubber Stamps", description: "High quality custom basic rubber stamps for your business needs.", image: "https://images.pexels.com/photos/3800021/pexels-photo-3800021.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Pocket Stamps", description: "High quality custom pocket stamps for your business needs.", image: "https://images.pexels.com/photos/8282361/pexels-photo-8282361.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Name Stamps", description: "High quality custom name stamps for your business needs.", image: "https://images.pexels.com/photos/4491444/pexels-photo-4491444.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Paper Embosser", description: "High quality custom paper embosser for your business needs.", image: "https://images.pexels.com/photos/3800060/pexels-photo-3800060.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
  ],
  'marketing-materials': [
    { name: "Standees", description: "High quality custom standees for your business needs.", image: "https://images.pexels.com/photos/5650018/pexels-photo-5650018.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Posters", description: "High quality custom posters for your business needs.", image: "https://images.pexels.com/photos/6353839/pexels-photo-6353839.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Bulk Posters", description: "High quality custom bulk posters for your business needs.", image: "https://images.pexels.com/photos/4108233/pexels-photo-4108233.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Banners", description: "High quality custom banners for your business needs.", image: "https://images.pexels.com/photos/3964566/pexels-photo-3964566.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Tabletop Standees", description: "High quality custom tabletop standees for your business needs.", image: "https://images.pexels.com/photos/38755330/pexels-photo-38755330.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Foam Boards", description: "High quality custom foam boards for your business needs.", image: "https://images.pexels.com/photos/7180485/pexels-photo-7180485.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Tabletop Signs", description: "High quality custom tabletop signs for your business needs.", image: "https://images.pexels.com/photos/36823601/pexels-photo-36823601.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Tent Cards", description: "High quality custom tent cards for your business needs.", image: "https://images.pexels.com/photos/5868260/pexels-photo-5868260.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Acrylic Sign Holder", description: "High quality custom acrylic sign holder for your business needs.", image: "https://images.pexels.com/photos/5650018/pexels-photo-5650018.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Flyers", description: "High quality custom flyers for your business needs.", image: "https://images.pexels.com/photos/6353839/pexels-photo-6353839.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Brochures", description: "High quality custom brochures for your business needs.", image: "https://images.pexels.com/photos/4108233/pexels-photo-4108233.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Booklets", description: "High quality custom booklets for your business needs.", image: "https://images.pexels.com/photos/3964566/pexels-photo-3964566.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Bulk Flyers", description: "High quality custom bulk flyers for your business needs.", image: "https://images.pexels.com/photos/38755330/pexels-photo-38755330.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Postcards", description: "High quality custom postcards for your business needs.", image: "https://images.pexels.com/photos/7180485/pexels-photo-7180485.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Portable Backdrops", description: "High quality custom portable backdrops for your business needs.", image: "https://images.pexels.com/photos/36823601/pexels-photo-36823601.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Bookmarks", description: "High quality custom custom bookmarks for your business needs.", image: "https://images.pexels.com/photos/5868260/pexels-photo-5868260.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Promotional Canopy Tents", description: "High quality custom promotional canopy tents for your business needs.", image: "https://images.pexels.com/photos/5650018/pexels-photo-5650018.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Acrylic Signs", description: "High quality custom acrylic signs for your business needs.", image: "https://images.pexels.com/photos/6353839/pexels-photo-6353839.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Outdoor Signs", description: "High quality custom outdoor signs for your business needs.", image: "https://images.pexels.com/photos/4108233/pexels-photo-4108233.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Plastic Signboards", description: "High quality custom plastic signboards for your business needs.", image: "https://images.pexels.com/photos/3964566/pexels-photo-3964566.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Board Signs", description: "High quality custom board signs for your business needs.", image: "https://images.pexels.com/photos/38755330/pexels-photo-38755330.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Canvas Signs", description: "High quality custom canvas signs for your business needs.", image: "https://images.pexels.com/photos/7180485/pexels-photo-7180485.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Magnetic Car Signs", description: "High quality custom magnetic car signs for your business needs.", image: "https://images.pexels.com/photos/36823601/pexels-photo-36823601.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "LED Translite Sign Boards", description: "High quality custom led translite sign boards for your business needs.", image: "https://images.pexels.com/photos/5868260/pexels-photo-5868260.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "LED Lollipop Display", description: "High quality custom led lollipop display for your business needs.", image: "https://images.pexels.com/photos/5650018/pexels-photo-5650018.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "LED Clip-On Displays", description: "High quality custom led clip-on displays for your business needs.", image: "https://images.pexels.com/photos/6353839/pexels-photo-6353839.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Car Door Decals", description: "High quality custom car door decals for your business needs.", image: "https://images.pexels.com/photos/4108233/pexels-photo-4108233.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Promo Tables", description: "High quality custom promo tables for your business needs.", image: "https://images.pexels.com/photos/3964566/pexels-photo-3964566.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Logo Flags", description: "High quality custom custom logo flags for your business needs.", image: "https://images.pexels.com/photos/38755330/pexels-photo-38755330.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Menu Cards", description: "High quality custom menu cards for your business needs.", image: "https://images.pexels.com/photos/7180485/pexels-photo-7180485.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Foldable Pop Up Banners", description: "High quality custom foldable pop up banners for your business needs.", image: "https://images.pexels.com/photos/36823601/pexels-photo-36823601.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Loyalty Cards", description: "High quality custom loyalty cards for your business needs.", image: "https://images.pexels.com/photos/5868260/pexels-photo-5868260.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Gift Certificates", description: "High quality custom custom gift certificates for your business needs.", image: "https://images.pexels.com/photos/5650018/pexels-photo-5650018.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Button Badges", description: "High quality custom button badges for your business needs.", image: "https://images.pexels.com/photos/6353839/pexels-photo-6353839.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Paper Bags", description: "High quality custom paper bags for your business needs.", image: "https://images.pexels.com/photos/4108233/pexels-photo-4108233.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Tablecloths", description: "High quality custom custom tablecloths for your business needs.", image: "https://images.pexels.com/photos/3964566/pexels-photo-3964566.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Table Runners", description: "High quality custom table runners for your business needs.", image: "https://images.pexels.com/photos/38755330/pexels-photo-38755330.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Table Mats", description: "High quality custom table mats for your business needs.", image: "https://images.pexels.com/photos/7180485/pexels-photo-7180485.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Stretch Table Covers", description: "High quality custom stretch table covers for your business needs.", image: "https://images.pexels.com/photos/36823601/pexels-photo-36823601.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Full-Print Paper Bags", description: "High quality custom full-print paper bags for your business needs.", image: "https://images.pexels.com/photos/5868260/pexels-photo-5868260.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Fabric Standees", description: "High quality custom fabric standees for your business needs.", image: "https://images.pexels.com/photos/5650018/pexels-photo-5650018.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "QR Code Stand", description: "High quality custom qr code stand for your business needs.", image: "https://images.pexels.com/photos/6353839/pexels-photo-6353839.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "LED Display Stands", description: "High quality custom led display stands for your business needs.", image: "https://images.pexels.com/photos/4108233/pexels-photo-4108233.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "X-Banners", description: "High quality custom x-banners for your business needs.", image: "https://images.pexels.com/photos/3964566/pexels-photo-3964566.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Fabric Banners", description: "High quality custom fabric banners for your business needs.", image: "https://images.pexels.com/photos/38755330/pexels-photo-38755330.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Mesh Banners", description: "High quality custom mesh banners for your business needs.", image: "https://images.pexels.com/photos/7180485/pexels-photo-7180485.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Tension Fabric Displays", description: "High quality custom tension fabric displays for your business needs.", image: "https://images.pexels.com/photos/36823601/pexels-photo-36823601.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Sail Flags", description: "High quality custom sail flags for your business needs.", image: "https://images.pexels.com/photos/5868260/pexels-photo-5868260.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Table Flags", description: "High quality custom table flags for your business needs.", image: "https://images.pexels.com/photos/5650018/pexels-photo-5650018.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Hanging Flags", description: "High quality custom hanging flags for your business needs.", image: "https://images.pexels.com/photos/6353839/pexels-photo-6353839.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Tour Guide Flags", description: "High quality custom tour guide flags for your business needs.", image: "https://images.pexels.com/photos/4108233/pexels-photo-4108233.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Wall Mounted Flags", description: "High quality custom wall mounted flags for your business needs.", image: "https://images.pexels.com/photos/3964566/pexels-photo-3964566.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Rectangle Flags", description: "High quality custom rectangle flags for your business needs.", image: "https://images.pexels.com/photos/38755330/pexels-photo-38755330.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Teardrop Flags", description: "High quality custom teardrop flags for your business needs.", image: "https://images.pexels.com/photos/7180485/pexels-photo-7180485.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
  ],
  'packaging': [
    { name: "Custom Stickers", description: "High quality custom custom stickers for your business needs.", image: "https://images.pexels.com/photos/33714864/pexels-photo-33714864.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Sheet Stickers", description: "High quality custom sheet stickers for your business needs.", image: "https://images.pexels.com/photos/3080665/pexels-photo-3080665.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Shape Stickers", description: "High quality custom custom shape stickers for your business needs.", image: "https://images.pexels.com/photos/9594430/pexels-photo-9594430.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Sticker Singles", description: "High quality custom sticker singles for your business needs.", image: "https://images.pexels.com/photos/7987867/pexels-photo-7987867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "UV Ink Transfer Stickers", description: "High quality custom uv ink transfer stickers for your business needs.", image: "https://images.pexels.com/photos/12324202/pexels-photo-12324202.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Window Stickers", description: "High quality custom window stickers for your business needs.", image: "https://images.pexels.com/photos/4438137/pexels-photo-4438137.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Dome Stickers", description: "High quality custom dome stickers for your business needs.", image: "https://images.pexels.com/photos/4200424/pexels-photo-4200424.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "QR Code Stickers", description: "High quality custom qr code stickers for your business needs.", image: "https://images.pexels.com/photos/33714864/pexels-photo-33714864.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Visiting Card Stickers", description: "High quality custom visiting card stickers for your business needs.", image: "https://images.pexels.com/photos/3080665/pexels-photo-3080665.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Kraft Stickers", description: "High quality custom kraft stickers for your business needs.", image: "https://images.pexels.com/photos/9594430/pexels-photo-9594430.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Holographic Stickers", description: "High quality custom holographic stickers for your business needs.", image: "https://images.pexels.com/photos/7987867/pexels-photo-7987867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Metal Stickers", description: "High quality custom metal stickers for your business needs.", image: "https://images.pexels.com/photos/12324202/pexels-photo-12324202.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Labels", description: "High quality custom custom labels for your business needs.", image: "https://images.pexels.com/photos/4438137/pexels-photo-4438137.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Product & Packaging Labels", description: "High quality custom product & packaging labels for your business needs.", image: "https://images.pexels.com/photos/4200424/pexels-photo-4200424.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Return Address Labels", description: "High quality custom return address labels for your business needs.", image: "https://images.pexels.com/photos/33714864/pexels-photo-33714864.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Iron-on Labels", description: "High quality custom custom iron-on labels for your business needs.", image: "https://images.pexels.com/photos/3080665/pexels-photo-3080665.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Transparent Labels", description: "High quality custom transparent labels for your business needs.", image: "https://images.pexels.com/photos/9594430/pexels-photo-9594430.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Industrial Labels", description: "High quality custom industrial labels for your business needs.", image: "https://images.pexels.com/photos/7987867/pexels-photo-7987867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Shipping & Mailing Labels", description: "High quality custom shipping & mailing labels for your business needs.", image: "https://images.pexels.com/photos/12324202/pexels-photo-12324202.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Roll Label Stickers", description: "High quality custom roll label stickers for your business needs.", image: "https://images.pexels.com/photos/4438137/pexels-photo-4438137.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Hang Tags", description: "High quality custom hang tags for your business needs.", image: "https://images.pexels.com/photos/4200424/pexels-photo-4200424.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Folded Hang Tags", description: "High quality custom folded hang tags for your business needs.", image: "https://images.pexels.com/photos/33714864/pexels-photo-33714864.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Baggage Tags", description: "High quality custom baggage tags for your business needs.", image: "https://images.pexels.com/photos/3080665/pexels-photo-3080665.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Name Tags", description: "High quality custom name tags for your business needs.", image: "https://images.pexels.com/photos/9594430/pexels-photo-9594430.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Raised Foil Hang Tags", description: "High quality custom raised foil hang tags for your business needs.", image: "https://images.pexels.com/photos/7987867/pexels-photo-7987867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Self Adhesive Tapes", description: "High quality custom self adhesive tapes for your business needs.", image: "https://images.pexels.com/photos/12324202/pexels-photo-12324202.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Paper Bags", description: "High quality custom custom paper bags for your business needs.", image: "https://images.pexels.com/photos/4438137/pexels-photo-4438137.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Printed Carry Bags", description: "High quality custom printed carry bags for your business needs.", image: "https://images.pexels.com/photos/4200424/pexels-photo-4200424.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Premium Gift Bags", description: "High quality custom premium gift bags for your business needs.", image: "https://images.pexels.com/photos/33714864/pexels-photo-33714864.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Courier Bags", description: "High quality custom courier bags for your business needs.", image: "https://images.pexels.com/photos/3080665/pexels-photo-3080665.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Corrugated Boxes", description: "High quality custom corrugated boxes for your business needs.", image: "https://images.pexels.com/photos/9594430/pexels-photo-9594430.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Flat Mailer Boxes", description: "High quality custom flat mailer boxes for your business needs.", image: "https://images.pexels.com/photos/7987867/pexels-photo-7987867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Metallic Shopping Bags", description: "High quality custom metallic shopping bags for your business needs.", image: "https://images.pexels.com/photos/12324202/pexels-photo-12324202.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Customised Ribbons", description: "High quality custom customised ribbons for your business needs.", image: "https://images.pexels.com/photos/4438137/pexels-photo-4438137.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Die Cut Handle Bags", description: "High quality custom die cut handle bags for your business needs.", image: "https://images.pexels.com/photos/4200424/pexels-photo-4200424.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Full-Print Mailer Boxes", description: "High quality custom full-print mailer boxes for your business needs.", image: "https://images.pexels.com/photos/33714864/pexels-photo-33714864.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Promotional Product Boxes", description: "High quality custom promotional product boxes for your business needs.", image: "https://images.pexels.com/photos/3080665/pexels-photo-3080665.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Tuck Top Boxes", description: "High quality custom tuck top boxes for your business needs.", image: "https://images.pexels.com/photos/9594430/pexels-photo-9594430.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Lock Bottom Boxes", description: "High quality custom lock bottom boxes for your business needs.", image: "https://images.pexels.com/photos/7987867/pexels-photo-7987867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Auto Lock Bottom Boxes", description: "High quality custom auto lock bottom boxes for your business needs.", image: "https://images.pexels.com/photos/12324202/pexels-photo-12324202.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Chocolate Bar Boxes", description: "High quality custom chocolate bar boxes for your business needs.", image: "https://images.pexels.com/photos/4438137/pexels-photo-4438137.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Soap Boxes", description: "High quality custom soap boxes for your business needs.", image: "https://images.pexels.com/photos/4200424/pexels-photo-4200424.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Pull Out Boxes", description: "High quality custom pull out boxes for your business needs.", image: "https://images.pexels.com/photos/33714864/pexels-photo-33714864.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Popcorn Boxes", description: "High quality custom popcorn boxes for your business needs.", image: "https://images.pexels.com/photos/3080665/pexels-photo-3080665.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Burger Boxes", description: "High quality custom burger boxes for your business needs.", image: "https://images.pexels.com/photos/9594430/pexels-photo-9594430.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Frosted Slider Bags", description: "High quality custom frosted slider bags for your business needs.", image: "https://images.pexels.com/photos/7987867/pexels-photo-7987867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Transparent Seal Bags", description: "High quality custom transparent seal bags for your business needs.", image: "https://images.pexels.com/photos/12324202/pexels-photo-12324202.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Designer Shopping Bags", description: "High quality custom designer shopping bags for your business needs.", image: "https://images.pexels.com/photos/4438137/pexels-photo-4438137.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Luxury Shopping Bags", description: "High quality custom luxury shopping bags for your business needs.", image: "https://images.pexels.com/photos/4200424/pexels-photo-4200424.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Clear Plastic Cups", description: "High quality custom clear plastic cups for your business needs.", image: "https://images.pexels.com/photos/33714864/pexels-photo-33714864.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
  ],
  'apparel': [
    { name: "Men's T-Shirts", description: "High quality custom men's t-shirts for your business needs.", image: "https://images.pexels.com/photos/6256315/pexels-photo-6256315.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Women's T-Shirts", description: "High quality custom women's t-shirts for your business needs.", image: "https://images.pexels.com/photos/6256272/pexels-photo-6256272.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Kid's T-shirts", description: "High quality custom kid's t-shirts for your business needs.", image: "https://images.pexels.com/photos/8532616/pexels-photo-8532616.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Polyester T-shirts", description: "High quality custom polyester t-shirts for your business needs.", image: "https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Premium Men's Cotton T-Shirts", description: "High quality custom premium men's cotton t-shirts for your business needs.", image: "https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Full Sleeves T-Shirts", description: "High quality custom full sleeves t-shirts for your business needs.", image: "https://images.pexels.com/photos/18411516/pexels-photo-18411516.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Limited Edition Cotton T-Shirts", description: "High quality custom limited edition cotton t-shirts for your business needs.", image: "https://images.pexels.com/photos/6256315/pexels-photo-6256315.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Jack & Jones Printed T-Shirts", description: "High quality custom jack & jones printed t-shirts for your business needs.", image: "https://images.pexels.com/photos/6256272/pexels-photo-6256272.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "M&S Round Neck T-Shirts", description: "High quality custom m&s round neck t-shirts for your business needs.", image: "https://images.pexels.com/photos/8532616/pexels-photo-8532616.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Skechers Crew Neck T-Shirts", description: "High quality custom skechers crew neck t-shirts for your business needs.", image: "https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Levi's Cotton/Polo T-Shirts", description: "High quality custom levi's cotton/polo t-shirts for your business needs.", image: "https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Reebok Printed T-Shirts", description: "High quality custom reebok printed t-shirts for your business needs.", image: "https://images.pexels.com/photos/18411516/pexels-photo-18411516.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Men's/Women's Polo T-Shirts", description: "High quality custom men's/women's polo t-shirts for your business needs.", image: "https://images.pexels.com/photos/6256315/pexels-photo-6256315.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Premium Polo T-Shirts", description: "High quality custom premium polo t-shirts for your business needs.", image: "https://images.pexels.com/photos/6256272/pexels-photo-6256272.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Puma Polo T-shirts", description: "High quality custom puma polo t-shirts for your business needs.", image: "https://images.pexels.com/photos/8532616/pexels-photo-8532616.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Parx Premium Polo T-Shirts", description: "High quality custom parx premium polo t-shirts for your business needs.", image: "https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "US Polo Assn Polo T-Shirts", description: "High quality custom us polo assn polo t-shirts for your business needs.", image: "https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Adidas Polo T-Shirts", description: "High quality custom adidas polo t-shirts for your business needs.", image: "https://images.pexels.com/photos/18411516/pexels-photo-18411516.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Woodland Polo T-Shirts", description: "High quality custom woodland polo t-shirts for your business needs.", image: "https://images.pexels.com/photos/6256315/pexels-photo-6256315.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Monte Carlo Polo T-Shirt", description: "High quality custom monte carlo polo t-shirt for your business needs.", image: "https://images.pexels.com/photos/6256272/pexels-photo-6256272.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Arrow Tipping Polo T-Shirts", description: "High quality custom arrow tipping polo t-shirts for your business needs.", image: "https://images.pexels.com/photos/8532616/pexels-photo-8532616.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Dress Shirts", description: "High quality custom custom dress shirts for your business needs.", image: "https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Cambridge Dress Shirts", description: "High quality custom cambridge dress shirts for your business needs.", image: "https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Park Avenue Shirts", description: "High quality custom park avenue shirts for your business needs.", image: "https://images.pexels.com/photos/18411516/pexels-photo-18411516.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Fil-A-Fil Shirts", description: "High quality custom fil-a-fil shirts for your business needs.", image: "https://images.pexels.com/photos/6256315/pexels-photo-6256315.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Arrow Dress Shirts", description: "High quality custom arrow dress shirts for your business needs.", image: "https://images.pexels.com/photos/6256272/pexels-photo-6256272.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Bags", description: "High quality custom custom bags for your business needs.", image: "https://images.pexels.com/photos/8532616/pexels-photo-8532616.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "American Tourister Laptop Bags", description: "High quality custom american tourister laptop bags for your business needs.", image: "https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Harissons Laptop Bags", description: "High quality custom harissons laptop bags for your business needs.", image: "https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Adidas Duffle Bags", description: "High quality custom adidas duffle bags for your business needs.", image: "https://images.pexels.com/photos/18411516/pexels-photo-18411516.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Cotton/Jute Tote Bags", description: "High quality custom cotton/jute tote bags for your business needs.", image: "https://images.pexels.com/photos/6256315/pexels-photo-6256315.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Sports Jersey", description: "High quality custom sports jersey for your business needs.", image: "https://images.pexels.com/photos/6256272/pexels-photo-6256272.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Polo Jerseys", description: "High quality custom custom polo jerseys for your business needs.", image: "https://images.pexels.com/photos/8532616/pexels-photo-8532616.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "India Cricket Fan Jersey", description: "High quality custom india cricket fan jersey for your business needs.", image: "https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Adidas Track Suit", description: "High quality custom adidas track suit for your business needs.", image: "https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "US Polo Track Suit", description: "High quality custom us polo track suit for your business needs.", image: "https://images.pexels.com/photos/18411516/pexels-photo-18411516.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Caps", description: "High quality custom custom caps for your business needs.", image: "https://images.pexels.com/photos/6256315/pexels-photo-6256315.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Beanies Caps", description: "High quality custom beanies caps for your business needs.", image: "https://images.pexels.com/photos/6256272/pexels-photo-6256272.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Reflective Safety Vest", description: "High quality custom reflective safety vest for your business needs.", image: "https://images.pexels.com/photos/8532616/pexels-photo-8532616.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Aprons", description: "High quality custom custom aprons for your business needs.", image: "https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Lab Coats", description: "High quality custom lab coats for your business needs.", image: "https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Uniform Overcoats", description: "High quality custom uniform overcoats for your business needs.", image: "https://images.pexels.com/photos/18411516/pexels-photo-18411516.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Umbrellas", description: "High quality custom umbrellas for your business needs.", image: "https://images.pexels.com/photos/6256315/pexels-photo-6256315.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Customised Hoodies", description: "High quality custom customised hoodies for your business needs.", image: "https://images.pexels.com/photos/6256272/pexels-photo-6256272.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
  ],
  'winterwear': [
    { name: "Fleece Jackets", description: "High quality custom fleece jackets for your business needs.", image: "https://images.pexels.com/photos/769733/pexels-photo-769733.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Puffer Jackets", description: "High quality custom puffer jackets for your business needs.", image: "https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Winter Jacket - Sleeveless", description: "High quality custom winter jacket - sleeveless for your business needs.", image: "https://images.pexels.com/photos/1689731/pexels-photo-1689731.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Adidas Hoodies/Jackets", description: "High quality custom adidas hoodies/jackets for your business needs.", image: "https://images.pexels.com/photos/6299351/pexels-photo-6299351.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Levi's High Neck Zipper Jackets", description: "High quality custom levi's high neck zipper jackets for your business needs.", image: "https://images.pexels.com/photos/769733/pexels-photo-769733.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Crewneck Sweatshirts", description: "High quality custom crewneck sweatshirts for your business needs.", image: "https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Swiss Military Jackets/Hoodies", description: "High quality custom swiss military jackets/hoodies for your business needs.", image: "https://images.pexels.com/photos/1689731/pexels-photo-1689731.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Embroidered Sweaters", description: "High quality custom embroidered sweaters for your business needs.", image: "https://images.pexels.com/photos/6299351/pexels-photo-6299351.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
  ],
  'gifts': [
    { name: "Photo Albums", description: "High quality custom photo albums for your business needs.", image: "https://images.pexels.com/photos/1187317/pexels-photo-1187317.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Layflat Photo Albums", description: "High quality custom layflat photo albums for your business needs.", image: "https://images.pexels.com/photos/2082071/pexels-photo-2082071.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Canvas Prints", description: "High quality custom canvas prints for your business needs.", image: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Photo With Frame", description: "High quality custom photo with frame for your business needs.", image: "https://images.pexels.com/photos/1758144/pexels-photo-1758144.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Premium Photo Frames", description: "High quality custom premium photo frames for your business needs.", image: "https://images.pexels.com/photos/1303098/pexels-photo-1303098.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Personalised Mugs", description: "High quality custom personalised mugs for your business needs.", image: "https://images.pexels.com/photos/3052136/pexels-photo-3052136.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Colour Changing Magic Mugs", description: "High quality custom colour changing magic mugs for your business needs.", image: "https://images.pexels.com/photos/1187317/pexels-photo-1187317.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Mugs Black", description: "High quality custom custom mugs black for your business needs.", image: "https://images.pexels.com/photos/2082071/pexels-photo-2082071.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Decorative Mugs", description: "High quality custom custom decorative mugs for your business needs.", image: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Vacuum Coffee Mugs", description: "High quality custom vacuum coffee mugs for your business needs.", image: "https://images.pexels.com/photos/1758144/pexels-photo-1758144.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Temperature Display Mugs", description: "High quality custom temperature display mugs for your business needs.", image: "https://images.pexels.com/photos/1303098/pexels-photo-1303098.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Gift Hampers", description: "High quality custom gift hampers for your business needs.", image: "https://images.pexels.com/photos/3052136/pexels-photo-3052136.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Travel Accessories Hampers", description: "High quality custom travel accessories hampers for your business needs.", image: "https://images.pexels.com/photos/1187317/pexels-photo-1187317.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Welcome Kit", description: "High quality custom welcome kit for your business needs.", image: "https://images.pexels.com/photos/2082071/pexels-photo-2082071.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Magnets / Fridge Magnets", description: "High quality custom custom magnets / fridge magnets for your business needs.", image: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Photo Magnets", description: "High quality custom photo magnets for your business needs.", image: "https://images.pexels.com/photos/1758144/pexels-photo-1758144.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Acrylic Photo Magnets", description: "High quality custom acrylic photo magnets for your business needs.", image: "https://images.pexels.com/photos/1303098/pexels-photo-1303098.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Customized Coasters", description: "High quality custom customized coasters for your business needs.", image: "https://images.pexels.com/photos/3052136/pexels-photo-3052136.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Acrylic Coasters", description: "High quality custom acrylic coasters for your business needs.", image: "https://images.pexels.com/photos/1187317/pexels-photo-1187317.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Soft/Tea Coasters", description: "High quality custom soft/tea coasters for your business needs.", image: "https://images.pexels.com/photos/2082071/pexels-photo-2082071.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Acrylic Photo Blocks", description: "High quality custom acrylic photo blocks for your business needs.", image: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Acrylic Display Stands", description: "High quality custom acrylic display stands for your business needs.", image: "https://images.pexels.com/photos/1758144/pexels-photo-1758144.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Acrylic Photo Prints", description: "High quality custom acrylic photo prints for your business needs.", image: "https://images.pexels.com/photos/1303098/pexels-photo-1303098.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Photo Frame", description: "High quality custom custom photo frame for your business needs.", image: "https://images.pexels.com/photos/3052136/pexels-photo-3052136.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "LED Photo Frames", description: "High quality custom led photo frames for your business needs.", image: "https://images.pexels.com/photos/1187317/pexels-photo-1187317.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Acrylic Photo Frame", description: "High quality custom acrylic photo frame for your business needs.", image: "https://images.pexels.com/photos/2082071/pexels-photo-2082071.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "LED Daily Journal Lamp", description: "High quality custom led daily journal lamp for your business needs.", image: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Personalized Wall Clocks", description: "High quality custom personalized wall clocks for your business needs.", image: "https://images.pexels.com/photos/1758144/pexels-photo-1758144.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Round Photo Mouse Pads", description: "High quality custom round photo mouse pads for your business needs.", image: "https://images.pexels.com/photos/1303098/pexels-photo-1303098.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Mouse Pads", description: "High quality custom custom mouse pads for your business needs.", image: "https://images.pexels.com/photos/3052136/pexels-photo-3052136.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Calendars", description: "High quality custom custom calendars for your business needs.", image: "https://images.pexels.com/photos/1187317/pexels-photo-1187317.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Magnet Calendars", description: "High quality custom magnet calendars for your business needs.", image: "https://images.pexels.com/photos/2082071/pexels-photo-2082071.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Corporate Gifts", description: "High quality custom corporate gifts for your business needs.", image: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
  ],
  'pens': [
    { name: "Customized / Personalised Pens", description: "High quality custom customized / personalised pens for your business needs.", image: "https://images.pexels.com/photos/2884144/pexels-photo-2884144.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Premium Magnetic Metal Roller Pens", description: "High quality custom premium magnetic metal roller pens for your business needs.", image: "https://images.pexels.com/photos/2900661/pexels-photo-2900661.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Wooden Finish Metal Ball Pens", description: "High quality custom wooden finish metal ball pens for your business needs.", image: "https://images.pexels.com/photos/811575/pexels-photo-811575.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Premium Matte Pens", description: "High quality custom premium matte pens for your business needs.", image: "https://images.pexels.com/photos/3819972/pexels-photo-3819972.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Premium Brass Metal Ball Pens", description: "High quality custom premium brass metal ball pens for your business needs.", image: "https://images.pexels.com/photos/2884144/pexels-photo-2884144.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Triangle Wire Clip Ball Pens", description: "High quality custom triangle wire clip ball pens for your business needs.", image: "https://images.pexels.com/photos/2900661/pexels-photo-2900661.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Submarine Sleek Metal Roller Pens", description: "High quality custom submarine sleek metal roller pens for your business needs.", image: "https://images.pexels.com/photos/811575/pexels-photo-811575.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Submarine Fountain Pens", description: "High quality custom submarine fountain pens for your business needs.", image: "https://images.pexels.com/photos/3819972/pexels-photo-3819972.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Value Pens", description: "High quality custom value pens for your business needs.", image: "https://images.pexels.com/photos/2884144/pexels-photo-2884144.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Executive Pens", description: "High quality custom executive pens for your business needs.", image: "https://images.pexels.com/photos/2900661/pexels-photo-2900661.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Premium Pens", description: "High quality custom premium pens for your business needs.", image: "https://images.pexels.com/photos/811575/pexels-photo-811575.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Luxury Pens", description: "High quality custom luxury pens for your business needs.", image: "https://images.pexels.com/photos/3819972/pexels-photo-3819972.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Promotional Pens", description: "High quality custom promotional pens for your business needs.", image: "https://images.pexels.com/photos/2884144/pexels-photo-2884144.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Gold Click Pens", description: "High quality custom gold click pens for your business needs.", image: "https://images.pexels.com/photos/2900661/pexels-photo-2900661.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Bulk Ball Pens", description: "High quality custom bulk ball pens for your business needs.", image: "https://images.pexels.com/photos/811575/pexels-photo-811575.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Multicolor Ball Pens", description: "High quality custom multicolor ball pens for your business needs.", image: "https://images.pexels.com/photos/3819972/pexels-photo-3819972.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Plastic Pens", description: "High quality custom plastic pens for your business needs.", image: "https://images.pexels.com/photos/2884144/pexels-photo-2884144.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Black Matte Ball/Roller Pens", description: "High quality custom black matte ball/roller pens for your business needs.", image: "https://images.pexels.com/photos/2900661/pexels-photo-2900661.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
  ],
  'drinkware': [
    { name: "Custom Water Bottles", description: "High quality custom custom water bottles for your business needs.", image: "https://images.pexels.com/photos/1342529/pexels-photo-1342529.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Customised Tumblers", description: "High quality custom customised tumblers for your business needs.", image: "https://images.pexels.com/photos/1187317/pexels-photo-1187317.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Cello Duro Kent Water Bottles", description: "High quality custom cello duro kent water bottles for your business needs.", image: "https://images.pexels.com/photos/338713/pexels-photo-338713.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Temperature Display Bottles", description: "High quality custom temperature display bottles for your business needs.", image: "https://images.pexels.com/photos/4183020/pexels-photo-4183020.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Stainless Steel Sipper Bottles", description: "High quality custom stainless steel sipper bottles for your business needs.", image: "https://images.pexels.com/photos/1207918/pexels-photo-1207918.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Vacuum Bottles", description: "High quality custom vacuum bottles for your business needs.", image: "https://images.pexels.com/photos/1342529/pexels-photo-1342529.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Cello Swift Bottles", description: "High quality custom cello swift bottles for your business needs.", image: "https://images.pexels.com/photos/1187317/pexels-photo-1187317.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Inox Bottles", description: "High quality custom inox bottles for your business needs.", image: "https://images.pexels.com/photos/338713/pexels-photo-338713.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Gym Bottles", description: "High quality custom gym bottles for your business needs.", image: "https://images.pexels.com/photos/4183020/pexels-photo-4183020.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Thermal Suction Bottles", description: "High quality custom thermal suction bottles for your business needs.", image: "https://images.pexels.com/photos/1207918/pexels-photo-1207918.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Pexpo Vacuum/Thermo Steel Bottles", description: "High quality custom pexpo vacuum/thermo steel bottles for your business needs.", image: "https://images.pexels.com/photos/1342529/pexels-photo-1342529.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Aluminium Water Bottles", description: "High quality custom aluminium water bottles for your business needs.", image: "https://images.pexels.com/photos/1187317/pexels-photo-1187317.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Wine Tumbler", description: "High quality custom wine tumbler for your business needs.", image: "https://images.pexels.com/photos/338713/pexels-photo-338713.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Travel Tumbler", description: "High quality custom travel tumbler for your business needs.", image: "https://images.pexels.com/photos/4183020/pexels-photo-4183020.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Vacuum Insulation Cup", description: "High quality custom vacuum insulation cup for your business needs.", image: "https://images.pexels.com/photos/1207918/pexels-photo-1207918.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Water Bottle with Wireless Speaker", description: "High quality custom water bottle with wireless speaker for your business needs.", image: "https://images.pexels.com/photos/1342529/pexels-photo-1342529.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Cello Flip Style Water Flasks", description: "High quality custom cello flip style water flasks for your business needs.", image: "https://images.pexels.com/photos/1187317/pexels-photo-1187317.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Insulated Vacuum Coffee Flasks", description: "High quality custom insulated vacuum coffee flasks for your business needs.", image: "https://images.pexels.com/photos/338713/pexels-photo-338713.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Frosted Beer Mugs", description: "High quality custom frosted beer mugs for your business needs.", image: "https://images.pexels.com/photos/4183020/pexels-photo-4183020.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Hip Flask", description: "High quality custom hip flask for your business needs.", image: "https://images.pexels.com/photos/1207918/pexels-photo-1207918.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Custom Matt Vacuum Bottles", description: "High quality custom custom matt vacuum bottles for your business needs.", image: "https://images.pexels.com/photos/1342529/pexels-photo-1342529.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Customised Beer Mugs", description: "High quality custom customised beer mugs for your business needs.", image: "https://images.pexels.com/photos/1187317/pexels-photo-1187317.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Personalised Champagne/Wine Glasses", description: "High quality custom personalised champagne/wine glasses for your business needs.", image: "https://images.pexels.com/photos/338713/pexels-photo-338713.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
    { name: "Personalised Vacuum Insulated Tumbler", description: "High quality custom personalised vacuum insulated tumbler for your business needs.", image: "https://images.pexels.com/photos/4183020/pexels-photo-4183020.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" },
  ],
};

export const popularProducts: Product[] = [
  {
    name: 'Visiting Cards',
    description: 'Premium business cards with custom finishes.',
    image: 'https://images.pexels.com/photos/9878733/pexels-photo-9878733.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Stack of blank business cards on marble',
  },
  {
    name: 'Flyers',
    description: 'Eye-catching flyers for promotions and events.',
    image: 'https://images.pexels.com/photos/5650018/pexels-photo-5650018.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Promotional sale signs on beige background',
  },
  {
    name: 'Brochures',
    description: 'Informative tri-fold and bi-fold brochures.',
    image: 'https://images.pexels.com/photos/2250136/pexels-photo-2250136.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Art magazines and brochures on concrete',
  },
  {
    name: 'Stickers',
    description: 'Custom die-cut stickers in any shape.',
    image: 'https://images.pexels.com/photos/33714864/pexels-photo-33714864.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Pile of custom stickers on wooden surface',
  },
  {
    name: 'Posters',
    description: 'High-quality posters in various sizes.',
    image: 'https://images.pexels.com/photos/4108233/pexels-photo-4108233.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Minimalist poster on a white wall',
  },
  {
    name: 'Banners',
    description: 'Large format flex and vinyl banners.',
    image: 'https://images.pexels.com/photos/5869617/pexels-photo-5869617.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Person holding a sale poster',
  },
  {
    name: 'ID Cards',
    description: 'Professional ID cards with lanyards.',
    image: 'https://images.pexels.com/photos/7108127/pexels-photo-7108127.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'ID badges on a gray surface',
  },
  {
    name: 'Letterheads',
    description: 'Branded letterheads for official correspondence.',
    image: 'https://images.pexels.com/photos/7718630/pexels-photo-7718630.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Minimalist office desk with supplies',
  },
  {
    name: 'Packaging',
    description: 'Custom packaging boxes and paper bags.',
    image: 'https://images.pexels.com/photos/3080665/pexels-photo-3080665.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Eco-friendly paper bags with rope handles',
  },
];

export const customerSegments: CustomerSegment[] = [
  {
    title: 'Startups',
    icon: 'Rocket',
    items: ['Visiting Cards', 'Letterheads', 'Brochures', 'Stickers'],
    image: 'https://images.pexels.com/photos/8059661/pexels-photo-8059661.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Business cards on textured marble background',
  },
  {
    title: 'Retail Businesses',
    icon: 'Store',
    items: ['Shop Boards', 'Posters', 'Banners', 'Packaging'],
    image: 'https://images.pexels.com/photos/3964566/pexels-photo-3964566.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Printed banner on building wall',
  },
  {
    title: 'Restaurants & Cafés',
    icon: 'UtensilsCrossed',
    items: ['Menus', 'Packaging', 'Stickers', 'Promotional Materials'],
    image: 'https://images.pexels.com/photos/7564198/pexels-photo-7564198.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Brown paper bag with thank you note',
  },
  {
    title: 'Salons & Beauty',
    icon: 'Scissors',
    items: ['Business Cards', 'Price Lists', 'Posters', 'Promotional Materials'],
    image: 'https://images.pexels.com/photos/5706015/pexels-photo-5706015.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Business cards on pastel orange background',
  },
  {
    title: 'Events & Weddings',
    icon: 'PartyPopper',
    items: ['Invitations', 'Banners', 'Standees', 'Event Materials'],
    image: 'https://images.pexels.com/photos/15313106/pexels-photo-15313106.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Wedding invitations with rustic bouquet',
  },
  {
    title: 'Real Estate',
    icon: 'Building2',
    items: ['Brochures', 'Boards', 'Flyers', 'Property Marketing Materials'],
    image: 'https://images.pexels.com/photos/29452731/pexels-photo-29452731.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Collection of travel brochures on display',
  },
];

export const featuredProducts: Product[] = [
  {
    name: 'Premium Visiting Cards',
    description: 'Spot UV, foil stamping, and premium finishes.',
    image: 'https://images.pexels.com/photos/5706020/pexels-photo-5706020.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Stack of blank business cards on pastel surface',
  },
  {
    name: 'Custom Stickers',
    description: 'Die-cut stickers with vibrant colors.',
    image: 'https://images.pexels.com/photos/12324202/pexels-photo-12324202.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'ISO certification stickers on paper',
  },
  {
    name: 'Business Brochures',
    description: 'Professional multi-fold brochures.',
    image: 'https://images.pexels.com/photos/7180485/pexels-photo-7180485.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Two people reviewing a design brochure',
  },
  {
    name: 'Custom Packaging',
    description: 'Branded boxes and bags for products.',
    image: 'https://images.pexels.com/photos/9594430/pexels-photo-9594430.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Hands packing a cardboard box with tags',
  },
  {
    name: 'Event Banners',
    description: 'Large format banners for events.',
    image: 'https://images.pexels.com/photos/38755330/pexels-photo-38755330.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Colorful theatre festival posters',
  },
  {
    name: 'Custom T-Shirts',
    description: 'Screen and heat-transfer printed apparel.',
    image: 'https://images.pexels.com/photos/6256315/pexels-photo-6256315.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Person wearing a custom printed t-shirt',
  },
];

export const businessSolutions: BusinessSolution[] = [
  {
    title: 'Branding Essentials',
    description: 'Logos, business cards, letterheads and brand identity materials.',
    icon: 'Palette',
  },
  {
    title: 'Marketing Materials',
    description: 'Flyers, brochures, posters and promotional campaign prints.',
    icon: 'Megaphone',
  },
  {
    title: 'Packaging Solutions',
    description: 'Custom boxes, labels, bags and product packaging.',
    icon: 'Package',
  },
  {
    title: 'Corporate & Promotional',
    description: 'Corporate gifts, apparel, event materials and merchandise.',
    icon: 'Gift',
  },
];

export const processSteps: ProcessStep[] = [
  {
    step: 1,
    title: 'Choose Your Product',
    description: 'Browse our range of printing products and select what you need.',
    icon: 'MousePointerClick',
  },
  {
    step: 2,
    title: 'Share Your Design or Requirement',
    description: 'Send us your design file or tell us what you need designed.',
    icon: 'FileUp',
  },
  {
    step: 3,
    title: 'Get Your Quote',
    description: 'We provide a quotation based on your specifications and quantity.',
    icon: 'Calculator',
  },
  {
    step: 4,
    title: 'We Print. You Collect.',
    description: 'Your prints are produced and ready for collection.',
    icon: 'PackageCheck',
  },
];

export const portfolioItems: PortfolioItem[] = [
  { title: 'Business Cards', category: 'Business', image: 'https://images.pexels.com/photos/8947634/pexels-photo-8947634.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Business cards on textured fabric' },
  { title: 'Tri-fold Brochure', category: 'Marketing', image: 'https://images.pexels.com/photos/36823601/pexels-photo-36823601.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Folded brochures with product design' },
  { title: 'Promotional Flyer', category: 'Marketing', image: 'https://images.pexels.com/photos/5868260/pexels-photo-5868260.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Person with sale poster on yellow background' },
  { title: 'Custom Packaging', category: 'Packaging', image: 'https://images.pexels.com/photos/7987867/pexels-photo-7987867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Red and black paper bags on black background' },
  { title: 'Product Stickers', category: 'Packaging', image: 'https://images.pexels.com/photos/33714864/pexels-photo-33714864.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Pile of stickers on wooden surface' },
  { title: 'Event Poster', category: 'Marketing', image: 'https://images.pexels.com/photos/4108233/pexels-photo-4108233.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Minimalist poster on white wall' },
  { title: 'Flex Banner', category: 'Branding', image: 'https://images.pexels.com/photos/3964566/pexels-photo-3964566.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Printed banner on building wall' },
  { title: 'Wedding Invitation', category: 'Events', image: 'https://images.pexels.com/photos/20074173/pexels-photo-20074173.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Peach envelopes with wax seals' },
  { title: 'Custom T-Shirt', category: 'Branding', image: 'https://images.pexels.com/photos/6256272/pexels-photo-6256272.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Custom printed t-shirt' },
  { title: 'ID Cards', category: 'Business', image: 'https://images.pexels.com/photos/7648025/pexels-photo-7648025.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Conference name badges on table' },
  { title: 'Paper Bags', category: 'Packaging', image: 'https://images.pexels.com/photos/3080665/pexels-photo-3080665.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Eco-friendly paper bags with rope handles' },
  { title: 'Event Standee', category: 'Events', image: 'https://images.pexels.com/photos/6353839/pexels-photo-6353839.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', alt: 'Person holding a rectangular poster' },
];

export const portfolioFilters = ['All', 'Business', 'Marketing', 'Packaging', 'Events', 'Branding'];

export const whyChooseItems: WhyChooseItem[] = [
  { title: 'Professional Printing', description: 'High-quality printing with attention to detail on every order.', icon: 'Printer' },
  { title: 'Design Assistance', description: 'In-house design support to bring your ideas to life.', icon: 'PenTool' },
  { title: 'Wide Range of Products', description: 'From business cards to banners — all your printing needs covered.', icon: 'LayoutGrid' },
  { title: 'Custom Printing Solutions', description: 'Tailored printing for unique sizes, materials and finishes.', icon: 'Settings2' },
  { title: 'Business & Event Printing', description: 'Solutions for both corporate and event printing requirements.', icon: 'Briefcase' },
  { title: 'Local Hyderabad Service', description: 'Conveniently located in Dilsukhnagar for easy access.', icon: 'MapPin' },
];

export const faqItems: FAQItem[] = [
  { question: 'What printing services do you provide?', answer: 'We provide a wide range of printing services including visiting cards, brochures, flyers, posters, banners, stickers, labels, packaging, invitations, ID cards, letterheads, signage, apparel printing and more.' },
  { question: 'Can I provide my own design?', answer: 'Yes, you can share your own print-ready design files with us. We accept common formats and will guide you on the specifications needed for the best print quality.' },
  { question: 'Do you provide designing services?', answer: 'Yes, our in-house design team can help create professional designs from your requirements. Just share your idea and we will turn it into a print-ready design.' },
  { question: 'How can I get a quotation?', answer: 'You can request a quote through the enquiry form on this page, call us, or message us on WhatsApp. Share your product type, quantity and specifications for an accurate quote.' },
  { question: 'Do you handle bulk printing orders?', answer: 'Yes, we handle both small and bulk printing orders. Whether you need a few dozen business cards or thousands of flyers, we can accommodate your requirements.' },
  { question: 'How long does printing take?', answer: 'Turnaround time depends on the product, quantity and design complexity. We will provide an estimated timeline along with your quotation.' },
  { question: 'Do you provide delivery?', answer: 'Please contact us to discuss delivery options for your order. We can share details based on your location and requirements.' },
  { question: 'Can I order custom sizes?', answer: 'Yes, we offer custom sizes for most of our products. Let us know your required dimensions and we will produce accordingly.' },
];

export const trustItems = [
  { title: 'Quality Printing', icon: 'BadgeCheck' },
  { title: 'Professional Design', icon: 'PenTool' },
  { title: 'Wide Product Range', icon: 'LayoutGrid' },
  { title: 'Local Hyderabad Service', icon: 'MapPin' },
];

export const navLinks = [
  { label: 'Home', href: '/#home' },
  { label: 'Services', href: '/#services' },
  { label: 'Products', href: '/#products' },
  { label: 'Business Solutions', href: '/#business-solutions' },
  { label: 'Portfolio', href: '/#portfolio' },
  { label: 'About', href: '/#about' },
  { label: 'Contact', href: '/#contact' },
  { label: 'Admin', href: '/admin' },
];
